// Shared option lists for the profile editors (EditProfile dialog + inline
// section editing on the profile page).

export const skillOptions = [
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "GraphQL",
  "REST API",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "PHP",
  "Laravel",
  "Ruby",
  "Ruby on Rails",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Git",
  "GitHub",
  "GitLab",
  "HTML",
  "CSS",
  "SASS",
  "LESS",
  "Redux",
  "MobX",
  "Jest",
  "Mocha",
  "Cypress",
  "Testing Library",
  "Webpack",
  "Babel",
  "ESLint",
  "Prettier",
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "SciPy",
  "R",
  "Tableau",
  "Power BI",
  "Hadoop",
  "Spark",
  "Big Data",
  "C",
  "C++",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Unity",
  "Web Design",
  "UI/UX",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
];

export const interestOptions = [
  "Web Development",
  "Mobile Development",
  "Game Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Cloud Computing",
  "DevOps",
  "Cybersecurity",
  "Blockchain",
  "IoT",
  "AR/VR",
  "Quantum Computing",
  "Robotics",
  "Open Source",
  "UI/UX Design",
  "Product Management",
  "Agile",
  "Scrum",
  "Project Management",
  "Technical Writing",
  "Teaching/Mentoring",
  "Competitive Programming",
  "Hackathons",
  "Startups",
  "Research",
  "Computer Graphics",
  "Computer Vision",
  "Natural Language Processing",
  "Data Engineering",
  "Backend Development",
  "Frontend Development",
  "Full Stack Development",
  "Systems Programming",
  "Low-level Programming",
  "Embedded Systems",
  "Network Programming",
  "Database Design",
  "Functional Programming",
  "Object-Oriented Programming",
];

export const departmentOptions = [
  { value: "AERO", label: "Aeronautical Engineering" },
  { value: "CSC", label: "Computer Science & Cybersecurity" },
  { value: "CSD", label: "Computer Science & Data Science" },
  { value: "CSE", label: "Computer Science & Engineering" },
  { value: "CSM", label: "Computer Science & ML" },
  { value: "CSIT", label: "Computer Science & IT" },
  { value: "IT", label: "Information Technology" },
  { value: "ECE", label: "Electronics & Communication Engineering" },
  { value: "MECH", label: "Mechanical Engineering" },
  { value: "EEE", label: "Electrical & Electronics Engineering" },
];

// Education levels, ordered School -> Engineering. A stream/branch does not
// apply to School.
export const educationLevels = [
  "School",
  "Intermediate",
  "Diploma",
  "Engineering",
];

export const LEVEL_WITHOUT_STREAM = "School";

// Stream for this level is always the user's department, not free text
export const LEVEL_WITH_DEPARTMENT_STREAM = "Engineering";

export const scoreTypes = ["CGPA", "Percentage"];

// Highest allowed value per score type (minimum is 0.00 for both)
export const scoreLimits = { CGPA: 10, Percentage: 100 };
