name: Deploy CodeStats

on:
  push:
    branches:
      - version-2.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "Loading NVM..."

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            echo "Node Version:"
            node -v

            echo "NPM Version:"
            npm -v

            echo "Moving to project directory..."
            cd /home/ubuntu/scope-cohorts

            echo "Updating source code..."
            git fetch origin
            git checkout version-2.0.0
            git reset --hard origin/version-2.0.0

            echo "Installing frontend dependencies..."
            cd frontend
            npm install

            echo "Building frontend..."
            npm run build

            echo "Deploying frontend..."
            sudo rm -rf /var/www/codestats/*
            sudo cp -R dist/* /var/www/codestats/

            echo "Restarting nginx..."
            sudo systemctl restart nginx

            echo "Installing backend dependencies..."
            cd ../backend
            npm install

            echo "Restarting backend..."
            pm2 restart all
            pm2 save

            echo "Deployment completed successfully!"